config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'web/welcome#index'

  scope module: :web do
    resource :login, only: %i[new create destroy]
    resources :users, only: %i[new create]
    resources :notes, only: %i[index new]
  end

  namespace :api do
    namespace :v1 do
      resources :notes
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :full_name, presence: true
  validates :email, presence: true
end

app/controllers/api/v1/application_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApplicationController < ActionController::Base
      include AuthenticationHelper

      def require_login
        return true if signed_in?

        render json: { error: "You're not authenticated" }
      end
    end
  end
end

app/controllers/api/v1/notes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class NotesController < ApplicationController
      before_action :require_login

      def index
        notes = Note.all
        render json: notes
      end

      def create
        note = Note.new(note_params)
        if note.save
          render json: { success: true, message: 'Note has been created' }
        else
          render json: { success: false, message: note.errors.full_messages.join(', ') }
        end
      end

      private

      def note_params
        params.require(:note).permit(:title, :body)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include AuthenticationHelper

  def require_login
    return true if signed_in?

    redirect_to new_login_path
  end
end

app/controllers/web/login_controller.rb
# frozen_string_literal: true

module Web
  class LoginController < ApplicationController
    def new
      @form = LoginForm.new
    end

    def create
      user = User.find_by(email: form_params[:email])
      if user&.authenticate(form_params[:password])
        sign_in(user)
        redirect_to notes_path
      else
        flash.now[:error] = 'Email or password was invalid'
        render :new
      end
    end

    private

    def form_params
      params.require(:login_form).permit(:email, :password)
    end
  end
end

app/controllers/web/logins_controller.rb
# frozen_string_literal: true

module Web
  class LoginsController < ApplicationController
    def new
      @form = LoginForm.new
    end

    def create
      user = User.find_by(email: form_params[:email])
      if user&.authenticate(form_params[:password])
        sign_in(user)
        redirect_to notes_path
      else
        flash.now[:error] = 'Email or password was invalid'
        render :new
      end
    end

    def destroy
      logout
      redirect_to root_path
    end

    private

    def form_params
      params.require(:login_form).permit(:email, :password)
    end
  end
end

app/controllers/web/notes_controller.rb
# frozen_string_literal: true

module Web
  class NotesController < ApplicationController
    before_action :require_login

    def index; end

    def new; end
  end
end

app/controllers/web/users_controller.rb
# frozen_string_literal: true

module Web
  class UsersController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success_message] = 'Registration has been succeed'
        redirect_to new_user_path
      else
        flash.now[:error_message] = @user.errors.full_messages.join(', ')
        render :new
      end
    end

    private

    def user_params
      params.require(:user).permit(:full_name, :email, :password)
    end
  end
end

app/controllers/web/welcome_controller.rb
# frozen_string_literal: true

module Web
  class WelcomeController < ApplicationController
    def index; end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authentication_helper.rb
# frozen_string_literal: true

module AuthenticationHelper
  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find_by(id: user_id)
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def signed_in?
    return false if current_user.blank?

    true
  end

  def logout
    session[:user_id] = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleTddRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="app">
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |_, value| %>
  <%= value %>
<% end %>

app/views/web/login/new.html.erb
<%= form_with(model: @form, url: login_index_path, method: :post, local: true) do |form| %>
  <p>
    <%= form.label :email  %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.submit "Login" %>
  </p>
<% end %>

app/views/web/logins/new.html.erb
<%= form_with(model: @form, url: login_path, method: :post, local: true) do |form| %>
  <p>
    <%= form.label :email  %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.submit "Login" %>
  </p>
<% end %>

app/views/web/notes/index.html.erb
<p>Hi, <%= current_user.full_name %></p>
<p><%= link_to 'Logout', login_path, method: :delete %></p>
<h4>Dashboard</h4>
<%= link_to 'Add new note', new_note_path %>

<notes></notes>

app/views/web/notes/new.html.erb
<%= link_to 'Back to note list', notes_path %>

<add-note></add-note>

app/views/web/users/new.html.erb
<h4>User Registration</h4>

<%= form_with model: @user, url: users_path, method: :post, local: true do |form| %>
  <p>
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </p>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </p>
  <p>
    <%= form.submit "Submit" %>
  </p>
<% end %>

app/views/web/welcome/index.html.erb
<h1>Example tdd-in-rails web app</h1>

<%= link_to 'Daftar', new_user_path %>
<%= link_to 'Login', new_login_path %>